USE activity_db;

CREATE TABLE IF NOT EXISTS `locations` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(150) NOT NULL,
    `code` VARCHAR(50),
    `type` VARCHAR(50) NOT NULL,
    `description` TEXT,
    `address` VARCHAR(255),
    `building` VARCHAR(100),
    `floor_label` VARCHAR(50),
    `room` VARCHAR(50),
    `capacity` INT,
    `manager_department_id` BIGINT,
    `manager_user_id` BIGINT,
    `contact_name` VARCHAR(100),
    `contact_phone` VARCHAR(30),
    `is_bookable` TINYINT DEFAULT 1,
    `availability_status` VARCHAR(30) DEFAULT 'AVAILABLE',
    `is_active` TINYINT DEFAULT 1,
    `unavailable_reason` TEXT,
    `note` TEXT,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_locations_code` (`code`),
    KEY `idx_locations_type` (`type`),
    KEY `idx_locations_manager_department` (`manager_department_id`),
    KEY `idx_locations_bookable` (`is_active`, `is_bookable`, `availability_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `activity_location_bookings` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `activity_id` BIGINT NOT NULL,
    `location_id` BIGINT NOT NULL,
    `schedule_id` BIGINT,
    `title` VARCHAR(255),
    `start_time` DATETIME NOT NULL,
    `end_time` DATETIME NOT NULL,
    `status` TINYINT DEFAULT 0,
    `requested_by` BIGINT,
    `approved_by` BIGINT,
    `approved_at` DATETIME,
    `rejected_reason` TEXT,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `fk_location_booking_activity` (`activity_id`),
    KEY `fk_location_booking_location` (`location_id`),
    KEY `fk_location_booking_schedule` (`schedule_id`),
    KEY `idx_location_booking_lookup` (`location_id`, `status`, `start_time`, `end_time`),
    KEY `idx_location_booking_activity_status` (`activity_id`, `status`),
    CONSTRAINT `fk_location_booking_activity` FOREIGN KEY (`activity_id`) REFERENCES `activities`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_location_booking_location` FOREIGN KEY (`location_id`) REFERENCES `locations`(`id`) ON DELETE RESTRICT,
    CONSTRAINT `fk_location_booking_schedule` FOREIGN KEY (`schedule_id`) REFERENCES `activity_schedules`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
